### ISSUE TITLE
"第二十二章  3. 普通动词加 -ing " 内容缺失.

### ISSUE THREAD

**Issue by bestoml** [codeyu/EnglishGrammarBook#10]
http://grammar.codeyu.com/#docs/ReducedClauses#3--%E6%99%AE%E9%80%9A%E5%8A%A8%E8%AF%8D%E5%8A%A0--ing

缺失内容: 参考:进阶文法简体版.

        The runner [who finished second] won a small prize.
        先行词          关系从句
        (跑第二名的选手赢得一笔小额奖金。)
        
        关系从句 who finished second 修饰先行词 the runner。关系从句的主语 who 和先行词重
复，因而有可以减化的空间。减化的做法是省略掉关系从句主语 who，然后把关系从句的动
词减化为非限定动词。因为这个动词（finished）里面没有 be 动词也没有语气助动词，所以
可以先这样修改：把 who finished second 改写为 who was finishing second。这样做的目的并
不是要改成进行时，而是为了做词类变化：把限定动词 finished 改为现在分词 finishing、成
为主语补语保留下来，动词变成无意义的 was 可以连同重复的主语 who 一并省略，关系子
句 who finished second 就可以减化为现在分词词组 finishing second，整个句子减化如下：
        The runner [finishing second] won a small prize.
        先行词         减化关系从句

**Comment by codeyu** [comment]
fixed. thank you:)
